### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by TeoSean** [megascatterbomb/MegaAntiCheat#19]
Hey, love what you're doing for tf2.

Just a couple questions:

- What exactly is the tech stack for this project? 
- What exactly is the use of the local database? If it still communicates with the master, it's still writing the same amount of data to the masterbase, and doesn't really take much load off the master. 
- Is the masterbase going to be monolithic or a cluster?

Funding:
- Should this project go global, who exactly is paying for this? Hosting and maintenance fees for a global project aren't cheap.

**Comment by thejaviertc** [comment]
Now that Github Discussions are enabled, maybe this should be moved there

**Comment by TeoSean** [comment]
OK, moved to discussions.
