### ISSUE TITLE
Revisit error throwing in player.ts

### ISSUE THREAD

**Issue by MartinSchenkel** [megascatterbomb/MegaAntiCheat#39]
Following the discussion on #38 the following code in player.ts should be revisited to address the concerns raised by @FinnDore

https://github.com/megascatterbomb/MegaAntiCheat/blob/a21e666c6d0864640aca79090e3b6c14f8c861b5/local/src/client/player.ts#L36 https://github.com/megascatterbomb/MegaAntiCheat/blob/a21e666c6d0864640aca79090e3b6c14f8c861b5/local/src/client/player.ts#L46

**Comment by Bash-09** [comment]
See https://github.com/megascatterbomb/MegaAntiCheat/pull/38#issuecomment-1595774995

**Comment by MartinSchenkel** [comment]
Perfect, I'd count that as revisited :)
